# Generated by Django 4.2.3 on 2023-09-15 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cost_of_order',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
