# Generated by Django 4.2.3 on 2023-08-25 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_products_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ('item_name',)},
        ),
        migrations.AddField(
            model_name='products',
            name='sold',
            field=models.IntegerField(default=0),
        ),
    ]
