# Generated by Django 4.2.3 on 2023-09-15 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_order_cost_of_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExceptionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('exception_message', models.TextField()),
                ('exception_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
