# Generated by Django 4.2.3 on 2023-08-25 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_products_options_products_sold'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promo_image', models.BinaryField(blank=1, editable=True, null=True)),
                ('promo_name', models.CharField(max_length=100)),
                ('promo_description', models.TextField()),
            ],
        ),
    ]
