# Generated by Django 4.2.3 on 2023-08-26 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_promoitems'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ('item_name',), 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='promoitems',
            options={'verbose_name_plural': 'Promo Items'},
        ),
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.BinaryField(blank=1, null=True),
        ),
    ]
