# Generated by Django 4.2.3 on 2023-09-25 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_sale'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailySales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_sale', models.DateField(auto_now_add=True)),
                ('total_sales', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_quantity', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Daily Sales',
            },
        ),
        migrations.RenameField(
            model_name='order',
            old_name='ordered',
            new_name='delivered',
        ),
    ]
