# Generated by Django 4.2.3 on 2023-08-26 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_products_options_alter_promoitems_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
    ]
