# Generated by Django 4.2.3 on 2023-09-29 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_order_cost_of_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cost_of_order',
        ),
    ]
