# Generated by Django 4.2.3 on 2023-08-31 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_producttestupload'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producttestupload',
            old_name='product_image',
            new_name='image_binary',
        ),
    ]
