# Generated by Django 4.2.3 on 2023-08-31 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_rename_product_image_producttestupload_image_binary'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producttestupload',
            options={'verbose_name_plural': 'Product Test Upload'},
        ),
        migrations.AddField(
            model_name='cart',
            name='cart_key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
