# Generated by Django 4.2.3 on 2023-08-31 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_producttestupload_options_cart_cart_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='product',
            field=models.JSONField(),
        ),
    ]
