# Generated by Django 4.2.3 on 2023-09-01 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_cart_buyer_remove_cart_cart_key_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnonymousCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AnonymousCartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.anonymouscart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.products')),
            ],
        ),
        migrations.AddField(
            model_name='anonymouscart',
            name='cart_items',
            field=models.ManyToManyField(through='core.AnonymousCartItem', to='core.products'),
        ),
    ]
