# Generated by Django 4.2.3 on 2023-09-01 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_rename_cart_items_anonymouscart_products_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
