# Generated by Django 4.2.3 on 2023-09-01 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_cartitem_total_cost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='total_cost',
            new_name='sub_total',
        ),
        migrations.AddField(
            model_name='cart',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
