# Generated by Django 4.2.3 on 2023-09-02 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_rename_total_cost_cartitem_sub_total_cart_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='anonymouscart',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='anonymouscartitem',
            name='sub_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
