# Generated by Django 4.2.3 on 2023-09-02 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_buyerdeliverydetails_alter_order_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
