# Generated by Django 4.2.3 on 2023-09-02 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyerdeliverydetails',
            name='country',
            field=models.CharField(default='Croatia', max_length=100),
        ),
    ]
