# Generated by Django 4.2.3 on 2023-09-02 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_buyerdeliverydetails_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyerdeliverydetails',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
