# Generated by Django 4.2.3 on 2023-09-02 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_order_buyer_id_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigVariables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_email', models.EmailField(max_length=254)),
                ('store_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('store_address', models.CharField(blank=True, max_length=200, null=True)),
                ('store_postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('store_city', models.CharField(blank=True, max_length=100, null=True)),
                ('store_country', models.CharField(default='Croatia', max_length=100)),
                ('store_name', models.CharField(blank=True, max_length=100, null=True)),
                ('store_description', models.TextField()),
                ('store_logo', models.BinaryField(blank=1, null=True)),
                ('store_favicon', models.BinaryField(blank=1, null=True)),
                ('store_facebook', models.CharField(blank=True, max_length=100, null=True)),
                ('store_instagram', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
